language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  project: ./build/
  domain: darbandi.surge.sh
on:
  branch: master

